services:
  pgvector:
    image: 'pgvector/pgvector:pg17'
    environment:
      # - 'POSTGRES_DB=markets'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'